import {
  Search,
  Bell,
  ChevronDown,
  ChevronRight,
  Check,
  Star,
  ShieldCheck,
  MessageSquare,
  Heart,
  Lock,
  Mail,
  User,
  ArrowRight,
  X,
  Menu,
  Plus,
  MoreHorizontal,
  Eye,
  Clock,
  Package,
  LogOut,
  Sparkles,
  LayoutGrid,
  Send,
  BadgeCheck,
  Wallet,
  TrendingUp,
  Info,
  Trash2,
  Pencil,
  Briefcase,
  Home,
  SlidersHorizontal,
  Calendar,
  Download,
  Image,
  MapPin,
  AtSign,
} from 'lucide-react'

const iconMap = {
  search: Search,
  bell: Bell,
  chevDown: ChevronDown,
  chevRight: ChevronRight,
  check: Check,
  star: Star,
  starFill: Star,
  halfstar: Star,
  shield: ShieldCheck,
  chat: MessageSquare,
  heart: Heart,
  lock: Lock,
  mail: Mail,
  user: User,
  arrowRight: ArrowRight,
  x: X,
  menu: Menu,
  plus: Plus,
  more: MoreHorizontal,
  eye: Eye,
  clock: Clock,
  box: Package,
  image: Image,
  logout: LogOut,
  sparkles: Sparkles,
  grid: LayoutGrid,
  send: Send,
  verified: BadgeCheck,
  wallet: Wallet,
  trend: TrendingUp,
  info: Info,
  trash: Trash2,
  edit: Pencil,
  briefcase: Briefcase,
  home: Home,
  sliders: SlidersHorizontal,
  calendar: Calendar,
  download: Download,
  mapPin: MapPin,
  'at-sign': AtSign,
}

export default function Icon({ name, size = 20, className = '', strokeWidth = 2, fill = 'none', align = null }) {
  const C = iconMap[name] || Info
  return (
    <C
      size={size}
      strokeWidth={strokeWidth}
      fill={fill}
      className={`shrink-0 ${align === 'h' ? 'inline align-[-0.125em]' : ''} ${className}`}
    />
  )
}